spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 150
      maximum-pool-size: 150
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: credit

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

application:
  feign-url:
    fakeApi: localhost:3000

logging:
  level:
    org:
      springframework:
        transaction: debug
        data:
          mongodb.core.MongoTemplate: DEBUG
      hibernate:
        type:
          descriptor:
            sql: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 10
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        register-health-indicator: true

    instances:
      testCircuit:
        base-config: default
        minimum-number-of-calls: 1
        wait-duration-in-open-state: 5000
---
spring:
  config:
    activate:
      on-profile: test

application:
  feign-url:
    fakeApi: localhost:${wiremock.server.port}