spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 150
      maximum-pool-size: 150
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: credit

application:
  feign-url:
    fakeApi: localhost:3000


logging:
  level:
    org:
      springframework:
        transaction: debug
        data:
          mongodb.core.MongoTemplate: DEBUG
      hibernate:
        type:
          descriptor:
            sql: debug